[package]
name = "digitsrecog"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[[bin]]
name = "digitsrecog"
path = "src/main.rs"

[dependencies]
rand = "0.8.5"
serde = "1.0.147"
ciborium = "0.2.0"